### ISSUE TITLE
Can't use this plugin in a project with nuke-alamofire-plugin

### ISSUE THREAD

**Issue by elimence** [ryokosuge/Nuke-WebP-Plugin#33]
I tried installing this plugin in my project which already has `nuke-alamofire-plugin`. Looks like they have different requirements for Nuke. Here's the output from running `pod install`

```
[!] CocoaPods could not find compatible versions for pod "Nuke":
  In snapshot (Podfile.lock):
    Nuke (= 5.1.1, ~> 5.0)

  In Podfile:
    Nuke-Alamofire-Plugin was resolved to 2.0, which depends on
      Nuke (~> 5.0)

    Nuke-WebP-Plugin was resolved to 1.1.0, which depends on
      Nuke (~> 6.0)
```

Is there a way around this? All webP images in my app are not loading currently, I'd be grateful for any help, thanks :)

**Comment by ryokosuge** [comment]
@elimence Thank you for trying using the library I made!
The latest version of `Nuke-WebP-Plugin` I created corresponds only to Nuke 's version 7.0 or higher.

What version are you planning to use?
If you do not mind, please show me the contents of `Podfile` and` Podfile.lock`!
thanks :)
